
# * Numpy 

In [1]:
import pandas as pd 
import numpy as np 

In [6]:
#1d array
array1d = np.array([1,2,3,'name',None,3.22])
type(array1d)

numpy.ndarray

In [18]:
# 2d array
array2d = np.array([[1,2,3,4,5],[2,22,"aa",1,20150430_UKDebate.csv]])
print(array2d)
print("shape is: ", array2d.shape)
print('dimension is ',array2d.ndim)

[list([1, 2, 3, 4, 5]) list([2, 22, 'aa'])]
shape is:  (2,)
dimension is  1


In [24]:
# array
array2d_2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array2d_2)
array2d_2.ndim

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2

In [32]:
# three dimensional
array_3d = np.array([[[1,2,3],[1,2,3]],[[4,4,4],[1,2,4]]])
print(array_3d)
print("dimension is:",array_3d.ndim)
print("Shape is:",array_3d.shape)

[[[1 2 3]
  [1 2 3]]

 [[4 4 4]
  [1 2 4]]]
dimension is: 3
Shape is: (2, 2, 3)


In [42]:
# reshaping array
array1 = np.arange(20)
print(array1)
print(array1.shape,array1.ndim)

array2_2d = array1.reshape(2,10) # reshaping to 2d array
array2_3d = array1.reshape(2,2,5) # reshaping to 3d array

print(array2)
print(array2.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,) 1
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
2


In [45]:
# array is homogeneous

array3 = np.array([1,2,3,4])
print(array3.dtype)
print(array3*3)
#************************ difference between list and array*****in array '*' ans will be multiplication while in list disple n time
l1 = [1,2,3,4]
print(l1*3)

int32
[ 3  6  9 12]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [56]:
array4 = np.array([1,2,3,'a'])
print(array4)
print(array4.dtype)
array4[3]+'a' 
#print(array4*2) # its not possible-error

['1' '2' '3' 'a']
<U11


'aa'

In [65]:
array5 = np.array([1,2,3,4,8.2,0],dtype = 'i2')#integer of 2 bytes
print(array5)
print(array5.dtype)

[1 2 3 4 8 0]
int16


In [66]:
# convert int array to float
array7_i = np.array([1,2,3])
array7_f = array7_i.astype('f')
print(array7_f)
print(array7_f.dtype)
type(array7_i)

[1. 2. 3.]
float32


numpy.ndarray

In [69]:
# convert float array to int
array8_i = np.array([1.111,2,3,0.0,0.0])
array8_f = array8_i.astype('i')
print(array8_f)
print(array8_f.dtype)


[1 2 3 0 0]
int32


# * Indexing, Slicing, Joining, Spliting

In [ ]:
import numpy as np

#create 1d,2d,3d arrays

In [81]:
array1d = np.arange(20)
array2d = array1.reshape(2,10)
array3d = array1.reshape(4,1,5)
print(array1d)
print(array2d)
print(array3d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]

 [[15 16 17 18 19]]]


In [83]:
# indexing

print("4 th position in 1d:",array1d[3])
print('5th element on 2d array:',array2d[1,4])
print('')

4 th position in 1d: 3
5th element on 2d array: 14


In [90]:
print("5th element on _ dim in 1st array:", array3d[1,0,4])

5th element on 2 dim in 1st array: 9


In [91]:
# negative indexing
print("last element from 2nd dim:",array2[1,-1])

last element from 2nd dim: 19


In [92]:
# slicing
 # 1d array
print(array1d)
print(array1d[:7])

# 2d array ...first row from 1to 4
print(array2d)
print(array2d[0,1:4])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[1 2 3]


In [93]:
# slicing 2d from 2d
print(array2d)
print(array2d[:,1:4]) # from both rows take 1:4 values

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 1  2  3]
 [11 12 13]]


In [95]:
# join 1d array by concatination
data1 = np.array([1,2,3,4])
data2 = np.array([4,5,6,7])
newdata = np.concatenate((data1,data2))
newdata

array([1, 2, 3, 4, 4, 5, 6, 7])

In [104]:
# join 2d array by concate
data1 = np.array([[1,2,3,4],[2,2,1.2,0]])
data2 = np.array([[4,5,6,7],[3,3,0,11]])
newdata = np.concatenate((data1,data2))
print(newdata)
print(newdata.shape)


[[ 1.   2.   3.   4. ]
 [ 2.   2.   1.2  0. ]
 [ 4.   5.   6.   7. ]
 [ 3.   3.   0.  11. ]]
(4, 4)


In [101]:
# join 2d array by concate with Axis parameter
data1 = np.array([[1,2,3,4],[2,2,1.2,0]])
data2 = np.array([[4,5,6,7],[3,3,0,11]])
newdata = np.concatenate((data1,data2),axis=1)
newdata 

array([[ 1. ,  2. ,  3. ,  4. ,  4. ,  5. ,  6. ,  7. ],
       [ 2. ,  2. ,  1.2,  0. ,  3. ,  3. ,  0. , 11. ]])

In [105]:
# join using stack
data1 = np.array([[1,2,3,4],[2,2,1.2,0]])
data2 = np.array([[4,5,6,7],[3,3,0,11]])
newdata = np.stack((data1,data2))
print(newdata)
print(newdata.shape) # stack convert 2d to 3d

[[[ 1.   2.   3.   4. ]
  [ 2.   2.   1.2  0. ]]

 [[ 4.   5.   6.   7. ]
  [ 3.   3.   0.  11. ]]]
(2, 2, 4)


In [106]:
# to stack by rows
data1 = np.array([[1,2,3,4],[2,2,1.2,0]])
data2 = np.array([[4,5,6,7],[3,3,0,11]])
newdata = np.hstack((data1,data2))
print(newdata)
print(newdata.shape)

[[ 1.   2.   3.   4.   4.   5.   6.   7. ]
 [ 2.   2.   1.2  0.   3.   3.   0.  11. ]]
(2, 8)


In [107]:
# to stack by columns
data1 = np.array([[1,2,3,4],[2,2,1.2,0]])
data2 = np.array([[4,5,6,7],[3,3,0,11]])
newdata = np.vstack((data1,data2))
print(newdata)
print(newdata.shape)

[[ 1.   2.   3.   4. ]
 [ 2.   2.   1.2  0. ]
 [ 4.   5.   6.   7. ]
 [ 3.   3.   0.  11. ]]
(4, 4)


In [114]:
# spliting 1d array
data = np.array([1,2,3,4,5])
new_array = np.split(data,2.5)
print(new_array)
print(new_array[1])

[array([1, 2, 3]), array([4, 5])]
[4 5]


In [122]:
#split 2d array
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
new_array2 = np.split(data,2)
print(new_array2)
print(new_array2[0][0])

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
[1 2 3]


In [127]:
# split 2d based on axis
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
new_array2 = np.split(data,3,axis =1) # horizontal slicing
print(new_array2)


[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


# Iteration, manipulation, Random numbers

In [129]:
# iteration through elements of array
# iterate over 1d array

array1 = np.array([1,2,3,4])
i = 0
for x in array1:
    print(x)
    i=i+1
    print(i)


1
1
2
2
3
3
4
4


In [131]:
# iterate 2d array
array2 = np.array([[1,2,3],[3,4,5]])
# for x in array2:
#     print(x)
    
i=0
for x in array2:
    print(x)
    i=i+1
    print(i)

[1 2 3]
1
[3 4 5]
2


In [133]:
# iterate by elements in 2-d array
array3 = np.array([[1,2,3],[3,4,5]])
for i in array3:
    print(i)
    for j in i:
        print(j)

[1 2 3]
1
2
3
[3 4 5]
3
4
5


In [135]:
# iterate through 3-d array
array4 = np.array([[[1,2],[1,2]],[[3,4],[3,4]]])
#print(array4)
for x in array4:
    print(x)

[[1 2]
 [1 2]]
[[3 4]
 [3 4]]


In [141]:
# accesing all elements of 3d  level
array5 = np.array([[[1,2],[3,4]],[['a','b'],['c','d']]])
for i in array5:
    print("*****")
    print(i)
    for j in i:
        print(j)
        for k in j:
            print(k)
            



*****
[['1' '2']
 ['3' '4']]
['1' '2']
1
2
['3' '4']
3
4
*****
[['a' 'b']
 ['c' 'd']]
['a' 'b']
a
b
['c' 'd']
c
d


In [142]:
# using nditer and loop through array

array6 = np.array([[[1,2],[3,4]],[['a','b'],['c','d']]])
for i in np.nditer(array6):
    print(i)


1
2
3
4
a
b
c
d


In [145]:
# manipulation
## reshape 1d to higher dimension - use reshape
m_array1 = np.arange(25)
print(m_array1)
m_array2 = m_array1.reshape(5,5)
m_array2

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [147]:
# flatten - higher dimension to 1-d
m_array3 = m_array2.flatten()
m_array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [151]:
# transpose
m_array2.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [154]:
# roll axis ------- its like transpose
print(np.rollaxis(m_array2,1))

[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


In [155]:
# some other techniques ---join, slice, spliting

#********Random numbers

In [157]:
from numpy import random

In [160]:
random.rand(10)

numpy.ndarray

In [163]:
# random 1d array
r_ar1 = random.randint(10,size=(5))
print(r_ar1)


[1 1 6 8 7]


In [168]:
# random 2d array
r_ar2 = random.randint(100,size=(5,5))
r_ar2

array([[ 7, 62, 99, 73, 55],
       [55, 60, 48, 46, 54],
       [95, 75, 60,  9, 71],
       [50, 60, 19, 29, 20],
       [94, 80, 62, 84,  3]])

In [182]:
# random array with a specific distributation
r_arr3 = random.choice([1,2,3],p=[0.3,0.3,0.4],size =20)
r_arr3

array([2, 3, 2, 3, 3, 1, 2, 3, 1, 2, 2, 1, 2, 3, 3, 3, 3, 1, 2, 2])

# Array Operations

**************************************************
bitwise- 10 AND 11 - 1011 
string - adding character,capitalize and other case 
matematical - add,sub,mul,power
stat - AVG,median,percentile
**************************************************

In [ ]:
import numpy as np

In [188]:
# bitwise operator ,,,it will convert number to binary
num1 = 10
num2 = 11
print("Number 1:",num1,'Binary:',np.binary_repr(num1))
print("Number 1:",num2,'Binary:',np.binary_repr(num2))

Number 1: 10 Binary: 1010
Number 1: 11 Binary: 1011


In [195]:
# bitwise OR-AND
num1 = 10
num2 = 11
bitwise_OR_operator = np.bitwise_or(num1,num2)
bitwise_and_operator = np.bitwise_and(num1,num2)
print("Bitwise_or_operator:",bitwise_OR_operator,'binary_representation',np.binary_repr(bitwise_OR_operator))
print("Bitwise_and_operator:",bitwise_and_operator,'binary_representation',np.binary_repr(bitwise_and_operator))

Bitwise_or_operator: 11 binary_representation 1011
Bitwise_and_operator: 10 binary_representation 1010


In [198]:
# String operation - add same length arrays
str_ar1 = np.array(['a','b','c'])
str_ar2 = np.array(['x','y','z'])

np.char.add(str_ar1,str_ar2)

array(['ax', 'by', 'cz'], dtype='<U2')

In [199]:
#add different length arrays - itwill give erroe
str_ar1 = np.array(['a','b','c'])
str_ar2 = np.array(['x','y','z','e'])
np.char.add(str_ar1,str_ar2)

ValueError: shape mismatch: objects cannot be broadcast to a single shape

In [200]:
#
str_ar1 = np.array(['a','b','c'])
str_ar2 ='a'
np.char.add(str_ar1,str_ar2)

array(['aa', 'ba', 'ca'], dtype='<U2')

In [201]:
# string multiplication
str_ar1 = np.array(['a','b','c'])
np.char.multiply(str_ar1,3)

array(['aaa', 'bbb', 'ccc'], dtype='<U3')

In [202]:
# capitalization -------- it ll capitalise only 1st character
np.char.capitalize("learning DS")


array('Learning ds', dtype='<U11')

In [204]:
np.char.capitalize(np.char.multiply(str_ar1,3))

array(['Aaa', 'Bbb', 'Ccc'], dtype='<U3')

In [208]:
# lower to uper
np.char.upper(str_ar1)

array(['A', 'B', 'C'], dtype='<U1')

In [210]:
# uper to lower 
np.char.lower('MANSI')

array('mansi', dtype='<U5')

In [214]:
# strip empty spaces
str_ar3 = np.array([' x ',' y ',' z ','  '])
print(str_ar3)
print(np.char.strip(str_ar3))


[' x ' ' y ' ' z ' '  ']
['x' 'y' 'z' '']


In [215]:
# string operation - replace
np.char.replace(str_ar3,'x','a')

array([' a ', ' y ', ' z ', '  '], dtype='<U3')

In [217]:
# mathematical operation
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])

print("Addition:",ar1+ar2)
print("Addition:",ar1*ar2)
print("Addition:",ar1-ar2)

Addition: [5 7 9]
Addition: [ 4 10 18]
Addition: [-3 -3 -3]


In [221]:
# round-off
m_ar3 = np.array([2.3333,0,3.336,0.001])
print("round-off:",np.around(m_ar3,decimals=2))
print("Floor:",np.floor(m_ar3))
print("ceil:",np.ceil(m_ar3))

round-off: [2.33 0.   3.34 0.  ]
Floor: [2. 0. 3. 0.]
ceil: [3. 0. 4. 1.]


In [223]:
# power
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])
print(np.power(ar1,2))
print(np.power(ar1,ar2))

[1 4 9]
[  1  32 729]


In [241]:
# stat operations
ar4 = np.array([[4,5,6],[1,2,3],[7,8,9]])
print("Max:", np.amax(ar4))
print("Min:", np.amin(ar4))


Max: 9
Min: 1


In [239]:
# min max with axis

print("min is:",np.amin(ar4,1))

min is: [4 1 7]


In [244]:
# median
np.median(ar4)
np.median(ar4,1) -# for axis

array([5., 2., 8.])

In [251]:
# average , mean and variance
print("average:",np.average(ar4,0))
print("Mean:",np.mean(ar4,0))
print("Variance:",np.var(ar4,1))

average: [4. 5. 6.]
Mean: [4. 5. 6.]
Variance: [0.66666667 0.66666667 0.66666667]


In [252]:
# percentile
np.percentile(ar4,70,axis=0)

array([5.2, 6.2, 7.2])

# Sort,search,filter

In [ ]:
import numpy as np 

In [260]:
# sort 1d array
ar1 = np.random.randint(50,size=10)
print(ar1)
print(np.sort(ar1))

[41 24 18 18  0 31  4 14 10 19]
[ 0  4 10 14 18 18 19 24 31 41]


In [261]:
# to reverse order
np.sort(ar1)[::-1]

array([41, 31, 24, 19, 18, 18, 14, 10,  4,  0])

In [264]:
# sort string array
str_ar1= np.array(['x','b','c','ab','aa','a'])
np.sort(str_ar1)

array(['a', 'aa', 'ab', 'b', 'c', 'x'], dtype='<U2')

In [268]:
# sorting 2d array
ar_2d = np.array([[11,2,3,33],[24,55,22,6],[12,2,45,3]])
print(ar_2d)
print(np.sort(ar_2d))

[[11  2  3 33]
 [24 55 22  6]
 [12  2 45  3]]
[[ 2  3 11 33]
 [ 6 22 24 55]
 [ 2  3 12 45]]


In [271]:
# sorting 2d array with axis
print(np.sort(ar_2d,axis=0)) # column wise


[[11  2  3  3]
 [12  2 22  6]
 [24 55 45 33]]


In [272]:
print(np.sort(ar_2d,axis=0,kind = 'mergesort')) 

[[11  2  3  3]
 [12  2 22  6]
 [24 55 45 33]]


In [273]:
print(np.msort(ar_2d)) # sort based on first axis

[[11  2  3  3]
 [12  2 22  6]
 [24 55 45 33]]


In [ ]:
# search ***********

In [280]:
ar1 = np.random.randint(40,size=10)
ar2 = np.array([1,2,4,5,6])
print(ar1)
np.where(ar2==4)

[30  8 21  5 23 15 30 11 27 35]


(array([2], dtype=int64),)

In [282]:
# search position meeting criteria
np.where(ar2%2 ==0)

(array([1, 2, 4], dtype=int64),)

In [283]:
# to extract elements satisfying condition
np.extract(ar1%2==0,ar1)

array([30,  8, 30])

In [295]:
# where to insert the new value to retain the sort order
print(np.sort(ar1))
print(np.searchsorted(ar1,22))


[ 5  8 11 15 21 23 27 30 30 35]
8


In [296]:
# insert multiple values
print(np.searchsorted(ar1,[2,44,22]))

[ 0 10  8]


In [297]:
#**************************** positions of value****************
# find position of min and max values
np.argmin(ar1)

3

In [302]:
# 2d array -- return positions
ar_2d = np.array([[11,2,3,33],[24,55,22,1],[12,2,45,3]])
print(ar_2d)
print('position of min value:',np.argmin(ar_2d))
print('position of min value by rows:',np.argmin(ar_2d,axis=1))
print('position of min value by columns:',np.argmin(ar_2d,axis=0))

# max values
print('position of max value by columns:',np.argmax(ar_2d,axis=0))


[[11  2  3 33]
 [24 55 22  1]
 [12  2 45  3]]
position of min value: 7
position of min value by rows: [1 3 1]
position of min value by columns: [0 0 0 1]
position of max value by columns: [1 1 2 0]


In [311]:
# ****************filter *******************
ar_2d = np.array([[11,2,3,33],[24,55,22,1],[12,2,45,3]])
#condition = ar_2d>20 | ar_2d<45 

filterd_ar = ar_2d[(ar_2d>20) & (ar_2d<45)]
print(filterd_ar)

[33 24 22]


In [312]:
# ******************************************any / all******************
# are there any values greater than 9?
np.any(ar_2d>9)

True

In [313]:
# are all values equal to 6?
np.all(x == 6)

False